name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install bun
        run: npm install -g bun

      - name: Install dependencies
        run: bun i

      - name: Deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CERT_ARN: ${{ secrets.AWS_CERT_ARN }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          MIGRATE_DATABASE_URL: ${{ secrets.MIGRATE_DATABASE_URL }}
          MY_GITHUB_CLIENT_ID: ${{ secrets.MY_GITHUB_CLIENT_ID }}
          MY_GITHUB_CLIENT_SECRET: ${{ secrets.MY_GITHUB_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXT_PUBLIC_OPENAI_API_KEY: ${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}
          NEXT_PUBLIC_OPENAI_API_KEY_CHAT: ${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY_CHAT }}
          NEXT_PUBLIC_OPENAI_ENDPOINT: ${{ secrets.NEXT_PUBLIC_OPENAI_ENDPOINT }}
          NEXT_PUBLIC_OPENAI_ENDPOINT_CHAT: ${{ secrets.NEXT_PUBLIC_OPENAI_ENDPOINT_CHAT }}
          NEXT_PUBLIC_TOGETHERAI_API_KEY: ${{ secrets.NEXT_PUBLIC_TOGETHERAI_API_KEY }}
          FIREWORKS_AI_ENDPOINT: ${{ secrets.FIREWORKS_AI_ENDPOINT }}
          FIREWORKS_AI_API_KEY: ${{ secrets.FIREWORKS_AI_API_KEY }}
          TOGETHER_AI_API_KEY: ${{ secrets.TOGETHER_AI_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          STRIPE_STANDARD_MONTHLY_PLAN_ID: ${{ secrets.STRIPE_STANDARD_MONTHLY_PLAN_ID }}
          STRIPE_PRO_MONTHLY_PLAN_ID: ${{ secrets.STRIPE_PRO_MONTHLY_PLAN_ID }}
        run: |
          echo "Primsa generate"
          npx prisma generate
          echo "SST deploy"
          bun sst deploy --stage prod
